service: booking-system

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ${opt:region, 'eu-central-1'}
  stage: ${opt:stage, 'dev'}
  
  environment:
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}
    CV_BUCKET_NAME: riformaeprogresso-cvs
    NODE_ENV: ${self:provider.stage}
    ADMIN_USERNAME: ${env:ADMIN_USERNAME, 'admin'}
    ADMIN_PASSWORD: ${env:ADMIN_PASSWORD, 'replace_with_your_own'}
    CORS_ORIGINS: ${env:CORS_ORIGINS, '*'}
    GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID, ''}
    GOOGLE_CLIENT_SECRET: ${env:GOOGLE_CLIENT_SECRET, ''}
    ENABLE_GOOGLE_INTEGRATION: ${env:ENABLE_GOOGLE_INTEGRATION, 'false'}
  
  iam:
    role:
      statements:
        # DynamoDB permissions
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}/index/*"
        
        # SES permissions for email notifications
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
          Resource: "*"
        
        # S3 permissions for CV storage
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
            - s3:HeadObject
          Resource:
            - "arn:aws:s3:::riformaeprogresso-cvs/*"
        
        # S3 bucket permissions
        - Effect: Allow
          Action:
            - s3:ListBucket
          Resource:
            - "arn:aws:s3:::riformaeprogresso-cvs"

functions:
  api:
    handler: lambda-handler.handler
    timeout: 30
    memorySize: 512
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
      - http:
          path: /
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true

resources:
  Resources:
    # DynamoDB table for booking system data
    BookingSystemTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S
          - AttributeName: GSI2PK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: EntityType-Index
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: Slug-Index
            KeySchema:
              - AttributeName: GSI2PK
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        # Data backup (optional)
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 3000
  dotenv:
    path: .env